export const COPY = [
  { group: "Hlavička a patička", key: "site_name", label: "Název webu", value: "Kopidlenská drbna", max: 80 },
  { group: "Hlavička a patička", key: "brand_line", label: "Název, první řádek", value: "Kopidlenská", max: 40 },
  { group: "Hlavička a patička", key: "brand_accent", label: "Název, druhý řádek", value: "drbna", max: 40 },
  { group: "Hlavička a patička", key: "nav_news", label: "Menu: zprávy", value: "Zprávy", max: 40 },
  { group: "Hlavička a patička", key: "nav_events", label: "Menu: akce", value: "Akce", max: 40 },
  { group: "Hlavička a patička", key: "nav_ads", label: "Menu: reklamy", value: "Reklamy", max: 40 },
  { group: "Hlavička a patička", key: "nav_bins", label: "Menu: popelnice", value: "Popelnice", max: 40 },
  { group: "Hlavička a patička", key: "nav_yards", label: "Menu: sběrné dvory", value: "Sběrné dvory", max: 40 },
  { group: "Hlavička a patička", key: "nav_doctors", label: "Menu: lékaři", value: "Lékaři", max: 40 },
  { group: "Hlavička a patička", key: "nav_outages", label: "Menu: odstávky", value: "Odstávky", max: 40 },
  { group: "Hlavička a patička", key: "nav_about", label: "Menu: o nás", value: "O nás", max: 40 },
  { group: "Hlavička a patička", key: "menu_label", label: "Tlačítko menu na mobilu", value: "Menu", max: 40 },
  { group: "Hlavička a patička", key: "skip", label: "Odkaz přeskočit na obsah", value: "Přeskočit na obsah", max: 80 },
  { group: "Hlavička a patička", key: "link_whole", label: "Odkaz na celé noviny ze stránky svozu", value: "Celé noviny", max: 40 },
  { group: "Hlavička a patička", key: "footer_copy", label: "Patička, první řádek", value: "© 2026 Kopidlenská drbna", max: 120 },
  { group: "Hlavička a patička", key: "footer_fine", label: "Patička, upřesnění", value: "Neoficiální informační stránka — není provozována Městem Kopidlno.", max: 240, long: true },
  { group: "Hlavička a patička", key: "footer_admin", label: "Odkaz do redakce", value: "Redakce", max: 40 },

  { group: "Titulka", key: "home_description", label: "Popis titulky pro vyhledávače", value: "Místní zprávy a pozvánky pro Kopidlno a jeho části.", max: 240, long: true },
  { group: "Titulka", key: "hero_pill", label: "Štítek nad nadpisem", value: "Kopidlno a jeho části", max: 80 },
  { group: "Titulka", key: "hero_title", label: "Velký nadpis, první řádek", value: "Kopidlenská", max: 80 },
  { group: "Titulka", key: "hero_accent", label: "Velký nadpis, druhý řádek", value: "drbna", max: 40 },
  { group: "Titulka", key: "hero_lede", label: "Úvodní odstavec", value: "Místní zprávy, pozvánky a sousedské novinky z Kopidlna, Drahorazi, Mlýnce, Pševesi a Ledkova. Neúřední, přehledné a odsud.", max: 500, long: true },
  { group: "Titulka", key: "hero_alt", label: "Popis maskota", value: "Maskot Kopidlenské drbny, černobílý kozel", max: 160 },
  { group: "Titulka", key: "home_waste_eyebrow", label: "Nadpis u svozu na titulce", value: "Popelnice", max: 40 },
  { group: "Titulka", key: "home_waste_button", label: "Tlačítko na svoz", value: "Kdy se sváží", max: 40 },
  { group: "Titulka", key: "home_yards_button", label: "Tlačítko na sběrné dvory", value: "Sběrné dvory", max: 40 },
  { group: "Titulka", key: "home_doctors_button", label: "Tlačítko na lékaře", value: "Lékaři", max: 40 },
  { group: "Titulka", key: "home_outages_button", label: "Tlačítko na odstávky", value: "Odstávky", max: 40 },
  { group: "Titulka", key: "home_news_heading", label: "Nadpis sekce zpráv", value: "Zprávy", max: 40 },
  { group: "Titulka", key: "home_news_all", label: "Odkaz na všechny zprávy", value: "Všechny", max: 40 },
  { group: "Titulka", key: "home_events_heading", label: "Nadpis sekce akcí", value: "Akce", max: 40 },
  { group: "Titulka", key: "home_events_all", label: "Odkaz na kalendář", value: "Kalendář", max: 40 },
  { group: "Titulka", key: "empty_articles", label: "Když není žádná zpráva", value: "Zatím tu není žádná zpráva.", max: 200 },
  { group: "Titulka", key: "empty_events", label: "Když není žádná akce", value: "Zatím tu není zveřejněná pozvánka. Až ji redakce přidá, objeví se tady.", max: 240, long: true },

  { group: "Zprávy", key: "news_description", label: "Popis stránky zpráv", value: "Místní zprávy z Kopidlna a jeho částí.", max: 240, long: true },
  { group: "Zprávy", key: "news_eyebrow", label: "Malý nadpis stránky zpráv", value: "Rubrika", max: 40 },
  { group: "Zprávy", key: "news_heading", label: "Nadpis stránky zpráv", value: "Zprávy", max: 40 },
  { group: "Zprávy", key: "chip_all", label: "Filtr všech rubrik", value: "Vše", max: 40 },
  { group: "Zprávy", key: "cat_zpravy", label: "Název rubriky Zprávy", value: "Zprávy", max: 40 },
  { group: "Zprávy", key: "cat_komunita", label: "Název rubriky Komunita", value: "Komunita", max: 40 },
  { group: "Zprávy", key: "cat_kultura", label: "Název rubriky Kultura", value: "Kultura", max: 40 },
  { group: "Zprávy", key: "cat_prakticke", label: "Název rubriky Praktické", value: "Praktické", max: 40 },
  { group: "Zprávy", key: "cat_sport", label: "Název rubriky Sport", value: "Sport", max: 40 },
  { group: "Zprávy", key: "news_empty", label: "Prázdná rubrika", value: "V téhle rubrice zatím nic není.", max: 200 },
  { group: "Zprávy", key: "article_back", label: "Návrat na zprávy", value: "Zpět na zprávy", max: 80 },
  { group: "Zprávy", key: "missing_heading", label: "Chybějící zpráva", value: "Tahle zpráva tu není", max: 80 },
  { group: "Zprávy", key: "missing_description", label: "Popis chybějící zprávy", value: "Tahle zpráva tu není.", max: 160 },

  { group: "Akce", key: "events_description", label: "Popis stránky akcí", value: "Pozvánky z Kopidlna a okolních částí.", max: 240, long: true },
  { group: "Akce", key: "events_eyebrow", label: "Malý nadpis stránky akcí", value: "Kalendář", max: 40 },
  { group: "Akce", key: "events_heading", label: "Nadpis stránky akcí", value: "Akce", max: 40 },
  { group: "Akce", key: "events_lede", label: "Úvod stránky akcí", value: "Pozvánky z Kopidlna a okolních částí. Co tu není, redakce ještě nepřidala.", max: 400, long: true },
  { group: "Akce", key: "events_upcoming", label: "Nadpis nadcházejících akcí", value: "Chystá se", max: 40 },
  { group: "Akce", key: "events_upcoming_empty", label: "Když se nic nechystá", value: "Žádná zveřejněná pozvánka. Až bude, objeví se tady.", max: 240, long: true },
  { group: "Akce", key: "events_past", label: "Nadpis proběhlých akcí", value: "Už proběhlo", max: 40 },

  { group: "Popelnice", key: "bins_description", label: "Popis stránky svozu", value: "Nejbližší svoz směsného odpadu v Kopidlně.", max: 240, long: true },
  { group: "Popelnice", key: "bins_title", label: "Název stránky svozu", value: "Kdy se sváží", max: 40 },
  { group: "Popelnice", key: "bins_standalone", label: "Název samostatné stránky svozu", value: "Popelnice", max: 40 },
  { group: "Popelnice", key: "bins_pill", label: "Štítek nejbližšího svozu", value: "Nejbližší svoz", max: 40 },
  { group: "Popelnice", key: "bins_more", label: "Nadpis dalších termínů", value: "Další termíny", max: 40 },
  { group: "Popelnice", key: "bins_kind", label: "Druh odpadu", value: "Směsný komunální odpad", max: 80 },
  { group: "Popelnice", key: "bins_alt", label: "Popis fotky popeláře", value: "Kozel v montérkách s popelnicí na kopidlenském náměstí", max: 160 },
  { group: "Popelnice", key: "countdown_today", label: "Odpočet, svoz dnes", value: "Svoz je dnes.", max: 80 },
  { group: "Popelnice", key: "countdown_tomorrow", label: "Odpočet, svoz zítra", value: "Svoz je zítra.", max: 80 },
  { group: "Popelnice", key: "countdown_few", label: "Odpočet do 4 dnů, {n} je počet", value: "Za {n} dny.", max: 80 },
  { group: "Popelnice", key: "countdown_many", label: "Odpočet od 5 dnů, {n} je počet", value: "Za {n} dní.", max: 80 },
  { group: "Popelnice", key: "popelnice_label", label: "Text odkazu na původní svoz", value: "popelnice.kopidlenskadrbna.org", max: 120 },
  { group: "Popelnice", key: "popelnice_url", label: "Adresa původního svozu", value: "https://popelnice.kopidlenskadrbna.org/", max: 200 },
  { group: "Popelnice", key: "bins_yards_link", label: "Odkaz ze svozu na sběrné dvory", value: "Sběrné dvory", max: 80 },

  { group: "Sběrné dvory", key: "yards_description", label: "Popis stránky sběrných dvorů", value: "Sběrné dvory v Kopidlně: co se tam vozí, kdy mají otevřeno a kdy je mimořádně zavřeno.", max: 240, long: true },
  { group: "Sběrné dvory", key: "yards_eyebrow", label: "Malý nadpis stránky dvorů", value: "Odpad", max: 40 },
  { group: "Sběrné dvory", key: "yards_heading", label: "Nadpis stránky dvorů", value: "Sběrné dvory", max: 80 },
  { group: "Sběrné dvory", key: "yards_lede", label: "Úvod stránky dvorů", value: "Co se kam vozí a kdy mají otevřeno. Když je dvůr mimořádně zavřený, je tu i důvod. Není to úřední deska města.", max: 500, long: true },
  { group: "Sběrné dvory", key: "yards_empty", label: "Když není žádný dvůr", value: "Zatím tu není zveřejněný sběrný dvůr. Až ho redakce doplní, objeví se tady.", max: 240, long: true },
  { group: "Sběrné dvory", key: "yards_accepts", label: "Nadpis, co dvůr bere", value: "Co se sem vozí", max: 80 },
  { group: "Sběrné dvory", key: "yards_hours", label: "Nadpis otevírací doby", value: "Otevřeno", max: 40 },
  { group: "Sběrné dvory", key: "yards_closed", label: "Štítek mimořádného uzavření", value: "Mimořádně zavřeno", max: 80 },
  { group: "Sběrné dvory", key: "yards_upcoming", label: "Nadpis plánovaných uzavření", value: "Plánovaná uzavření", max: 80 },

  { group: "Lékaři", key: "doctors_description", label: "Popis stránky lékařů", value: "Ordinační hodiny lékařů v Kopidlně a dočasné změny, třeba zástup nebo jiná doba.", max: 240, long: true },
  { group: "Lékaři", key: "doctors_eyebrow", label: "Malý nadpis stránky lékařů", value: "Ordinace", max: 40 },
  { group: "Lékaři", key: "doctors_heading", label: "Nadpis stránky lékařů", value: "Lékaři", max: 80 },
  { group: "Lékaři", key: "doctors_lede", label: "Úvod stránky lékařů", value: "Ordinační hodiny v Kopidlně. Dopoledne a odpoledne mají vlastní čas a poznámku, třeba že jde jen o akutní případy. Dočasná změna je tu i s důvodem. Není to úřední deska města ani objednávkový systém.", max: 500, long: true },
  { group: "Lékaři", key: "doctors_empty", label: "Když není žádný lékař", value: "Zatím tu není zveřejněná ordinace. Až ji redakce doplní, objeví se tady.", max: 240, long: true },
  { group: "Lékaři", key: "doctors_hours", label: "Nadpis ordinačních hodin", value: "Ordinační hodiny", max: 40 },
  { group: "Lékaři", key: "doctors_regular", label: "Nadpis běžných hodin, když platí změna", value: "Běžné hodiny", max: 40 },
  { group: "Lékaři", key: "doctors_changes", label: "Nadpis dočasných změn", value: "Dočasné změny", max: 80 },
  { group: "Lékaři", key: "doctors_missing_hours", label: "Když hodiny ještě nejsou", value: "Ordinační hodiny zatím nejsou doplněné.", max: 160 },

  { group: "Odstávky", key: "outages_description", label: "Popis stránky odstávek", value: "Plánované odstávky elektřiny v Kopidlně a v obcích, které redakce hlídá.", max: 240, long: true },
  { group: "Odstávky", key: "outages_eyebrow", label: "Malý nadpis stránky odstávek", value: "Praktické", max: 40 },
  { group: "Odstávky", key: "outages_heading", label: "Nadpis stránky odstávek", value: "Odstávky elektřiny", max: 80 },
  { group: "Odstávky", key: "outages_lede", label: "Úvod stránky odstávek", value: "Přehled z veřejného widgetu ČEZ Distribuce. Není to úřední oznámení města a nemusí zachytit každou poruchu.", max: 500, long: true },
  { group: "Odstávky", key: "outages_empty", label: "Když žádná odstávka není", value: "V hlídaných obcích teď distributor nehlásí žádnou odstávku.", max: 240, long: true },
  { group: "Odstávky", key: "outages_none_watched", label: "Když se žádná obec nehlídá", value: "Redakce zatím nehlídá žádnou obec.", max: 240, long: true },
  { group: "Odstávky", key: "outages_waiting", label: "Když se přehled teprve načítá", value: "Přehled se právě načítá. Za chvíli tu bude.", max: 240, long: true },
  { group: "Odstávky", key: "outages_current", label: "Nadpis probíhající odstávky", value: "Právě bez proudu", max: 80 },
  { group: "Odstávky", key: "outages_planned", label: "Nadpis naplánovaných odstávek", value: "Naplánované", max: 80 },
  { group: "Odstávky", key: "outages_announcement", label: "Odkaz na oznámení", value: "Oznámení distributora (PDF)", max: 80 },
  { group: "Odstávky", key: "outages_source", label: "Odkaz na web distributora", value: "Ověřit na bezstavy.cz", max: 80 },
  { group: "Odstávky", key: "outages_disclaimer", label: "Odkud údaje bereme", value: "Drbna se ptá widgetu ČEZ několikrát denně a výsledek si schová. Když tu nic není, a proud přesto nejde, podívejte se na bezstavy.cz nebo zavolejte 800 850 860.", max: 500, long: true },

  { group: "O nás", key: "about_description", label: "Popis stránky O nás", value: "Sousedská, ne úřední stránka pro Kopidlno a jeho části.", max: 240, long: true },
  { group: "O nás", key: "about_eyebrow", label: "Malý nadpis stránky O nás", value: "O stránce", max: 40 },
  { group: "O nás", key: "about_heading", label: "Nadpis stránky O nás", value: "Sousedská, ne úřední", max: 80 },
  { group: "O nás", key: "about_lede", label: "Úvod stránky O nás", value: "Kopidlenská drbna je místní noviny pro Kopidlno, Drahoraz, Mlýnec, Pševes a Ledkov. Píšeme zprávy, pozvánky a praktické věci, hlavně kdy vyvézt popelnici.", max: 500, long: true },
  { group: "O nás", key: "about_disclaimer", label: "Upozornění, že nejde o úřad", value: "Stránku neprovozuje Město Kopidlno. Vyhlášky, poplatky a úřední oznámení berte vždy z webu města.", max: 500, long: true },
  { group: "O nás", key: "about_bins_link", label: "Odkaz na svoz", value: "Svoz popelnic", max: 80 },
  { group: "O nás", key: "about_yards_link", label: "Odkaz na sběrné dvory", value: "Sběrné dvory", max: 80 },
  { group: "O nás", key: "about_doctors_link", label: "Odkaz na lékaře", value: "Lékaři", max: 80 },
  { group: "O nás", key: "about_outages_link", label: "Odkaz na odstávky", value: "Odstávky elektřiny", max: 80 },
  { group: "O nás", key: "about_ads_link", label: "Odkaz na reklamy", value: "Reklamy", max: 80 },

  { group: "Reklamy", key: "ads_description", label: "Popis stránky reklam", value: "Neplacené místní reklamy z Kopidlna a jeho částí.", max: 240, long: true },
  { group: "Reklamy", key: "ads_eyebrow", label: "Malý nadpis stránky reklam", value: "Rubrika", max: 40 },
  { group: "Reklamy", key: "ads_heading", label: "Nadpis stránky reklam", value: "Reklamy", max: 80 },
  { group: "Reklamy", key: "ads_lede", label: "Úvod stránky reklam", value: "Neplacené nabídky od sousedů. Na panelu je napsáno, že jde o reklamu. Občas se stejný panel objeví i mezi zprávami nebo u pozvánky.", max: 500, long: true },
  { group: "Reklamy", key: "ads_empty", label: "Když není žádná reklama", value: "Zatím tu není žádná nabídka. Přidá ji kdokoli z redakce.", max: 240, long: true },
  { group: "Reklamy", key: "ads_back", label: "Návrat na reklamy", value: "Všechny reklamy", max: 80 },
  { group: "Reklamy", key: "ads_flag", label: "Označení panelu", value: "Reklama", max: 40 },
  { group: "Reklamy", key: "ads_sample", label: "Označení ukázky", value: "ukázka", max: 40 },
  { group: "Reklamy", key: "ads_more", label: "Text odkazu na panelu", value: "Víc", max: 40 },
  { group: "Reklamy", key: "ads_missing", label: "Chybějící reklama", value: "Tahle reklama tu není", max: 80 },
  { group: "O nás", key: "about_alt", label: "Popis maskota na stránce O nás", value: "Maskot Kopidlenské drbny", max: 160 },
];

const BY_KEY = new Map(COPY.map((item) => [item.key, item]));

export function text(copy, key) {
  const value = copy?.[key];
  if (typeof value === "string" && value.trim()) return value;
  return BY_KEY.get(key)?.value ?? "";
}
