// Čtení adres a formulářů redakce: co otevřít v okně a pole z odeslaného formuláře.
import { WEEK_DAYS } from "./yards.js";

function positiveParam(url, name) {
  const id = Number(url.searchParams.get(name));
  return Number.isInteger(id) && id > 0 ? id : undefined;
}

// Co má redakce otevřít v okně. Každá sekce si z toho vezme, co zná.
export function adminQuery(url) {
  return {
    fresh: url.searchParams.has("novy"),
    editingId: positiveParam(url, "id"),
    confirmId: positiveParam(url, "smazat"),
    proposalId: positiveParam(url, "navrh"),
    targetId: positiveParam(url, "clanek"),
    withdrawId: positiveParam(url, "stahnout"),
    discardId: positiveParam(url, "smazat-navrh"),
    cancelId: positiveParam(url, "zrusit"),
    closureYardId: positiveParam(url, "uzavreni"),
    hoursId: positiveParam(url, "hodiny"),
    changeId: positiveParam(url, "zmena"),
    newHoursId: positiveParam(url, "nova-doba"),
    offersId: positiveParam(url, "nabidka"),
    detailsId: positiveParam(url, "udaje"),
    linksId: positiveParam(url, "odkazy"),
    shareId: positiveParam(url, "sdilet"),
    accessId: positiveParam(url, "upravit"),
    disableId: positiveParam(url, "vypnout"),
    noticeId: positiveParam(url, "oznameni"),
    noticeFresh: url.searchParams.has("nove-oznameni"),
    closureFresh: url.searchParams.has("nova-uzavirka"),
    ndicClear: url.searchParams.has("ndic-smazat"),
    importId: positiveParam(url, "zprava"),
    importSettings: url.searchParams.has("nastaveni"),
    // Vložené příspěvky: okno Vložit příspěvek.
    paste: url.searchParams.has("vlozit"),
    // Akce v okolí: okno ručního článku Kam vyrazit.
    okoliWrite: url.searchParams.has("napsat"),
    topicId: positiveParam(url, "tema"),
    removeTopicId: positiveParam(url, "smazat-tema"),
    upload: url.searchParams.has("nahrat"),
    uploadTopicId: positiveParam(url, "nahrat"),
    freshTopic: url.searchParams.has("nove-tema"),
    clearChat: url.searchParams.has("smazat-otazky"),
    eventId: positiveParam(url, "akce"),
    requestId: positiveParam(url, "zadost"),
  };
}

export async function formFields(request) {
  const form = await request.formData();
  const text = (name) => String(form.get(name) ?? "");
  const positive = (name) => (Number.isInteger(Number(text(name))) && Number(text(name)) > 0 ? Number(text(name)) : undefined);
  const id = Number(text("id"));
  return {
    id: Number.isInteger(id) && id > 0 ? id : undefined,
    title: text("title"),
    excerpt: text("excerpt"),
    body: text("body"),
    category: text("category"),
    published: form.get("published") === "1",
    signedDrbena: form.get("signed_drbena") === "1",
    createdOn: text("created_on"),
    image: form.get("image"),
    imageFocus: text("image_focus"),
    imageCaption: text("image_caption"),
    // Zdroj zprávy pod čarou (src/article-source.js).
    source: text("source"),
    // Přílohy zprávy (src/attachments.js): formulář je ukázal a tyhle nechává, popisky a nově nahrané.
    attachmentsShown: text("attachments_shown") === "1",
    keepAttachments: form.getAll("keep_attachment").map(String),
    attachmentKeys: form.getAll("attachment_key").map(String),
    attachmentCaptions: form.getAll("attachment_caption").map(String),
    attachmentFiles: form.getAll("attachment_files"),
    newAttachmentCaptions: form.getAll("new_attachment_caption").map(String),
    place: text("place"),
    startsOn: text("startsOn"),
    // Akce je zrušená (formulář akce v redakci).
    eventCancelled: form.get("cancelled") === "1",
    startsTime: text("startsTime"),
    description: text("description"),
    // Akce: připojená zpráva, nebo zpráva psaná k akci. „Potom napsat zprávu“ u nové akce.
    eventArticleId: positive("zprava"),
    eventId: positive("akce"),
    writeArticle: text("potom") === "zprava",
    // Přihlášení kódem z e-mailu (src/login.js); `next` je stránka, kam se po přihlášení vrátit.
    loginCode: text("kod"),
    remember: text("neodhlasovat") === "1",
    // Odběr a data: zaškrtnuté vypínače feedů (src/feeds/settings.js).
    feedSwitches: form.getAll("feed").map(String),
    // Odběr a data: upozornění (src/push/store.js), vypínač a zapnutá témata.
    pushEnabled: text("push_enabled") === "1",
    pushTopics: form.getAll("push_topic").map(String),
    // E-mail na otevírací dobu: zaškrtnutá místa, lékaři a dvory adresy („sekce:id“, src/mailin/store.js).
    mailTargets: form.getAll("radek").map(String),
    // Můj účet: zaškrtnutá upozornění e-mailem (src/notify.js).
    notifySwitches: form.getAll("notify").map(String),
    token: text("token"),
    turnstile: text("cf-turnstile-response"),
    email: text("email"),
    name: text("name"),
    note: text("note"),
    active: text("active"),
    articleId: Number.isInteger(Number(text("clanek"))) && Number(text("clanek")) > 0 ? Number(text("clanek")) : undefined,
    next: text("next"),
    idleMinutes: text("idle_minutes"),
    maxDays: text("max_days"),
    sessionId: positive("zarizeni"),
    wasteNote: text("wasteNote"),
    holidayNote: text("holidayNote"),
    weekday: text("weekday"),
    weekParity: text("weekParity"),
    stepDays: text("stepDays"),
    accepts: text("accepts"),
    offers: text("offers"),
    week: WEEK_DAYS.map(({ day }) => ({
      day,
      open: form.get(`open-${day}`) === "1",
      from: text(`from-${day}`),
      to: text(`to-${day}`),
    })),
    endsOn: text("endsOn"),
    reason: text("reason"),
    alias: text("alias"),
    sortOrder: text("sortOrder"),
    yardId: Number.isInteger(Number(text("yardId"))) && Number(text("yardId")) > 0 ? Number(text("yardId")) : undefined,
    specialty: text("specialty"),
    phone: text("phone"),
    link: text("link"),
    enabled: form.get("enabled") === "1",
    // Akce v okolí: přepínače plánovaných článků Kam vyrazit (víkendy, volno se svátkem, samostatné svátky, týden).
    weekly: form.get("weekly") === "1",
    autoVolno: form.get("autoVolno") === "1",
    autoSvatek: form.get("autoSvatek") === "1",
    autoTyden: form.get("autoTyden") === "1",
    // Čas zveřejnění článků z nočního cronu (src/publish-time.js), u Kam vyrazit i pro týdenní článek.
    publishTime: text("publishTime"),
    weekPublishTime: text("weekPublishTime"),
    // Ruční článek Kam vyrazit na dny od–do.
    fromDay: text("od"),
    toDay: text("do"),
    closureId: text("closureId"),
    manual: text("manual"),
    radiusKm: text("radiusKm"),
    drbena: form.get("drbena") === "1",
    articleDays: text("articleDays"),
    adId: Number.isInteger(Number(text("nabidka"))) && Number(text("nabidka")) > 0 ? Number(text("nabidka")) : undefined,
    changeNote: text("changeNote"),
    placeId: Number.isInteger(Number(text("placeId"))) && Number(text("placeId")) > 0 ? Number(text("placeId")) : undefined,
    label: text("label"),
    doctorId: Number.isInteger(Number(text("doctorId"))) && Number(text("doctorId")) > 0 ? Number(text("doctorId")) : undefined,
    code: text("code"),
    parentId: Number.isInteger(Number(text("parentId"))) && Number(text("parentId")) > 0 ? Number(text("parentId")) : undefined,
    rubricId: Number.isInteger(Number(text("rubric_id"))) && Number(text("rubric_id")) > 0 ? Number(text("rubric_id")) : undefined,
    areas: form.getAll("areaId").map((id, index) => ({
      id: String(id),
      name: String(form.getAll("areaName")[index] ?? ""),
      code: String(form.getAll("areaCode")[index] ?? ""),
      sortOrder: String(form.getAll("areaSort")[index] ?? ""),
      enabled: form.getAll("areaOn").map(String).includes(String(id)),
    })),
    doctorWeek: WEEK_DAYS.map(({ day }) => ({
      day,
      morning: {
        open: form.get(`am-open-${day}`) === "1",
        from: text(`am-from-${day}`),
        to: text(`am-to-${day}`),
        note: text(`am-note-${day}`),
      },
      afternoon: {
        open: form.get(`pm-open-${day}`) === "1",
        from: text(`pm-from-${day}`),
        to: text(`pm-to-${day}`),
        note: text(`pm-note-${day}`),
      },
    })),
    permissions: form.getAll("permission").map((item) => String(item)),
    confirm: text("confirm") === "1",
    kind: text("kind"),
    // Návrh ke schválení (sběrné dvory, lékaři, otevírací doba) a důvod zamítnutí.
    requestId: positive("zadost"),
    reply: text("reply"),
    // Odkaz pro správce (src/hours-links-db.js): komu patří, zda zapisuje rovnou, a kdo změnu zapisuje.
    linkId: positive("odkaz"),
    targetId: positive("cil"),
    direct: form.get("direct") === "1",
    author: text("author"),
    endsTime: text("endsTime"),
    places: text("places"),
    sourceUrl: text("sourceUrl"),
    feedUrl: text("feedUrl"),
    feedUrls: text("feedUrls"),
    persona: text("persona"),
    chatAds: form.get("chatAds") === "1",
    ideas: text("ideas"),
    model: text("model"),
    perVisitor: text("perVisitor"),
    perDay: text("perDay"),
    budget: text("budget"),
    keepDays: text("keepDays"),
    archive: text("archive"),
    football: text("football"),
    articleText: text("text"),
    memory: form.get("memory") === "1",
    spread: form.get("spread") === "1",
    spreadFrom: text("spreadFrom"),
    spreadTo: text("spreadTo"),
    spreadMin: text("spreadMin"),
    spreadMax: text("spreadMax"),
    auto: form.get("auto") === "1",
    autoPublish: form.get("autoPublish") === "1",
    followupPublish: form.get("followupPublish") === "1",
    clubUrl: text("clubUrl"),
    truthUrl: text("truthUrl"),
    previews: form.get("previews") === "1",
    clubNews: form.get("clubNews") === "1",
    useCrest: form.get("useCrest") === "1",
    intervalHours: text("intervalHours"),
    ids: form.getAll("ids").map(Number),
    withFootball: form.get("withFootball") === "1",
    sourceLink: form.get("sourceLink") === "1",
    ownPhotos: form.get("ownPhotos") === "1",
    freshDays: text("freshDays"),
    aheadDays: text("aheadDays"),
    images: form.getAll("images"),
    // Vložený příspěvek (src/skola/paste.js).
    postText: text("postText"),
    postLink: text("postLink"),
    postFrom: text("postFrom"),
    postDate: text("postDate"),
    showPhotos: form.get("showPhotos") === "1",
    // Okno s konceptem: co udělat, fotka, den zveřejnění (čas je publishTime, rubrika rubric_id) a poznámka k přepsání.
    pasteAction: text("pasteAction"),
    photoChoice: text("photoChoice"),
    photoCaption: text("photoCaption"),
    publishDate: text("publishDate"),
    redoNote: text("redoNote"),
    stockId: positive("stock_id"),
    topicId: positive("topicId"),
    hint: text("hint"),
    fallbackTopicId: text("fallbackTopicId"),
    // Šipky pořadí v seznamu (otevírací doba): up nebo down.
    direction: text("direction"),
  };
}
